# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_add_first_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='First Title', max_length=200),
        ),
    ]
